Major overhaul of API, implemented Async compatible repeat/until_* nodes
jbcpollak/greenstalk pull request #10
Opened 2024-04-06 04:39 UTC by jbcpollak

2024-04-08 17:05 UTC, nivanov-ati requested changes

2024-04-08 17:05 UTC, nivanov-ati commented on common/decorator/until_failure_test.go
> +	for loop := true; loop; {
I think it's more canonical to do an infinite while loop here, like:

for {
....
}

and just do "break" on line 74

2024-04-08 17:05 UTC, nivanov-ati commented on common/decorator/until_success_test.go
> +	for loop := true; loop; {
same comment

2024-04-09 15:05 UTC, jbcpollak commented on common/decorator/repeat_until.go
> +	until UntilCondition
good point

2024-04-09 15:06 UTC, jbcpollak commented on common/decorator/until_failure_test.go
> +	for loop := true; loop; {
I started with that - the break breaks out of the select, not the for, AFAIK this is the only way to do this. 

@@fastcat is there a better way?

2024-04-09 15:09 UTC, nivanov-ati commented on common/decorator/until_failure_test.go
> +	for loop := true; loop; {
According to the tutorial, go doesnt need "break" in switch case statements, but I'm not sure if using one anyways would make it break out of `select` or `for`. It sounds like you tested it and it gets consumed by the select, so feel free to keep it as is

2024-04-09 15:22 UTC, jbcpollak commented on common/action/counter.go
> +func Counter[Blackboard any](params CounterParams) core.Node[Blackboard] {
probably not, but its a good example node and I figured hiding in a test-only directory would be more trouble than its worth.

2024-04-09 15:34 UTC, fastcat commented on common/decorator/until_failure_test.go
> +	for loop := true; loop; {
Use a label, I'll make a suggestion (requires a separate thread)

2024-04-09 15:34 UTC, nivanov-ati approved these changes

2024-04-09 15:34 UTC, merged

2024-04-09 15:35 UTC, fastcat commented on common/decorator/until_failure_test.go
> +	}
```suggestion
	LOOP: for {
		select {
		case c := <-countChan:
			log.Info().Msgf("got count %v", c)
		case c := <-sigChan:
			log.Info().Msgf("loop is finished %v", c)
			break LOOP
		case <-time.After(d):
			t.Errorf("Timeout after delaying %v", d)
		}
	}
```
(gofmt will move the label a bit, I wrote it this way to make the diff easier to view on GH)