added async function action
jbcpollak/greenstalk pull request #28
Opened 2024-07-30 20:16 UTC by nivanov-ati

2024-07-30 20:20 UTC, jbcpollak requested changes
needs unit test

2024-07-30 20:24 UTC, jbcpollak commented on common/action/async_function_action.go
> +	a.fnResult = a.Params.Func()
what if the function needs context information and/or BT params? Should we pass context and params in, or should Func() actually be an object with an interface that is constructed but the caller so they can pass any needed services or dependencies into the function?

2024-07-30 20:24 UTC, jbcpollak commented on common/action/async_function_action.go
> +	a.fnResult = a.Params.Func()
Note - a unit test or usage in a example project would help answer these questions

2024-07-30 20:48 UTC, nivanov-ati commented on common/action/async_function_action.go
> +	a.fnResult = a.Params.Func()
I agree re: unit test, but the overall structure is very similar to FunctionAction. Generally, I've been declaring function inside of a method with whatever parameters it needs (I forget what it's called - closure?)

2024-07-31 19:28 UTC, jbcpollak approved these changes

2024-07-31 19:28 UTC, merged